version: '3'

services:
  nodeapp:
    image: node:16-alpine
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ['npm','run','dev']